@HrHub.API_HostAddress = https://localhost:7080

Accept: application/json

###

GET {{HrHub.API_HostAddress}}/api/contenttype/[Action]

###

GET {{HrHub.API_HostAddress}}/api/contenttype/[Action]?id=0

###
